In [2]:
import numpy as np 
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [5]:
print(arr1.shape)
print(type(arr1))

(3,)
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(5,1)  

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [13]:
nums1 = np.ones((3,4))
print(nums1)

## Identity matrix 

nums = np.eye(3)
print(nums)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Universal Functions 
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
## Statistical concepts -- Normalisation

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation of the data 

mean = np.mean(data)
std_dev = np.std(data)

print("mean",mean,"standard deviation",std_dev)

mean 3.0 standard deviation 1.4142135623730951
